aws_region    = "us-east-1"
github_repo   = "https://github.com/ebrahimbeiati/inventory-management.git"
instance_type = "t2.micro"
vpc_cidr      = "10.0.0.0/16"
subnet_cidr   = "10.0.1.0/24"
environment   = "production" 